### ISSUE TITLE
broken link in project description

### ISSUE THREAD

**Issue by pseyfert** [jeromebelleman/beamer-cern#1]
The repository's description says

> A CERN LaTeX Beamer theme mimicking the official one http://cern.ch/jbl/tools/beamer-cern

Yet, http://cern.ch/jbl/tools/beamer-cern leads to a 404 error.

**Comment by jeromebelleman** [comment]
Indeed, it points to an old page which used to show the same contents as this project's GitHub page. I've removed the link.
